#!/bin/bash

# revno=`git rev-parse HEAD`
revno=`git rev-list --count HEAD`
cwd=`pwd`
dirname=`basename $cwd`

rm -f patch/VERSION-*
echo $revno > patch/VERSION-$revno
rm -f res/raw/patch.zip
zip -r res/raw/patch.zip patch
echo -e "<?xml version='1.0' encoding='utf-8'?>\n<resources>\n\t<integer name='revno'>$revno</integer>\n\t<string name='dirname'>$dirname</string>\n</resources>" > res/values/patch.xml
