#!/bin/bash

revno=`git log | grep -c commit`

for d in droidparty-demos droidparty-tests droidparty-abstractions;
do
	rm -f $d.zip
	zip -r $d.zip ../$d
done

rm PdDroidParty-debug.apk
cp ../bin/PdDroidParty-debug.apk PdDroidParty-debug-$revno.apk
ln -s PdDroidParty-debug-$revno.apk PdDroidParty-debug.apk

sed "s/PdDroidParty-debug-REVNO.apk*/PdDroidParty-debug-$revno.apk/g" index-template.html > index.html

rsync -avz . droidparty.net:/var/www/droidparty.net/
